const express = require('express');
const router = express.Router();
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const Invoice = require('../models/Invoice');
const jwt = require('jsonwebtoken');

// Ensure invoices directory exists
const invoiceDir = path.join(__dirname, '../uploads/invoices');
if (!fs.existsSync(invoiceDir)) {
    fs.mkdirSync(invoiceDir, { recursive: true });
}

const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, invoiceDir);
    },
    filename: function (req, file, cb) {
        cb(null, `invoice-${Date.now()}${path.extname(file.originalname)}`);
    }
});

const upload = multer({ storage: storage });

// Middleware to verify auth
const verifyAuth = async (req, res, next) => {
    try {
        const token = req.headers.authorization?.split(' ')[1];
        if (!token) return res.status(401).json({ success: false, message: 'No token provided' });

        const decoded = jwt.verify(token, process.env.JWT_SECRET);
        req.user = decoded;
        next();
    } catch (error) {
        res.status(401).json({ success: false, message: 'Invalid token' });
    }
};

// @route   POST /api/invoices/upload
// @desc    Upload an invoice generated by the frontend
router.post('/upload', verifyAuth, upload.single('invoicePdf'), async (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({ success: false, message: 'No file uploaded' });
        }

        const { paymentId, amount, description } = req.body;

        const newInvoice = new Invoice({
            user: req.user.id,
            paymentId,
            amount: parseFloat(amount),
            description,
            fileUrl: `/uploads/invoices/${req.file.filename}`
        });

        await newInvoice.save();

        res.status(201).json({ success: true, invoice: newInvoice });
    } catch (error) {
        console.error('Invoice upload error:', error);
        res.status(500).json({ success: false, message: 'Server error uploading invoice' });
    }
});

// @route   GET /api/invoices/user
// @desc    Get all invoices for the logged-in user
router.get('/user', verifyAuth, async (req, res) => {
    try {
        const invoices = await Invoice.find({ user: req.user.id }).sort({ date: -1 });
        res.json({ success: true, invoices });
    } catch (error) {
        console.error('Error fetching invoices:', error);
        res.status(500).json({ success: false, message: 'Server error fetching invoices' });
    }
});

module.exports = router;
